In [78]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
from PIL import Image
import numpy as np
import cv2

In [79]:
im_file = "data/page_01.jpg"
image = cv2.imread(im_file)

In [80]:
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print("Converted to grayscale image.")
cv2.imshow("img",gray_image)
cv2.waitKey(0)

Converted to grayscale image.


-1

In [81]:
# thresh=cv2.adaptiveThreshold(gray_image,200,230,cv2.THRESH_BINARY)[1]
#blur = cv2.GaussianBlur(gray_image,(5,5),0)
thresh=cv2.threshold(gray_image,210,230,cv2.THRESH_BINARY)[1]

print("Threshold Applied sucessfully.")
cv2.imshow("img",thresh)
cv2.waitKey(0)

Threshold Applied sucessfully.


-1

In [82]:
def noise_removal(image):
    no_noise = cv2.medianBlur(image, 5)
    return no_noise

def edge_detection(image):
    edges = cv2.Canny(image, 100, 200)
    return edges

def morphological_transform(image):
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 1))
    morph_image = cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel)
    return morph_image

In [87]:

# no_noise = noise_removal(thresh)

# edges = edge_detection(thresh)

morph_image = morphological_transform(thresh)

cv2.imshow("img",morph_image)
cv2.waitKey(0)

-1

In [88]:
from pytesseract import Output

# Extract recognized data from easy text
data = pytesseract.image_to_data(morph_image, output_type=Output.DICT)


In [ ]:
data

In [89]:
n_boxes = len(data["text"])
n_boxes

320

In [90]:
for i in range(n_boxes):
   if data["conf"][i] == -1:
       continue
   
   # Coordinates
   x, y = data["left"][i], data["top"][i]
   w, h = data["width"][i], data["height"][i]

   # Corners
   top_left = (x, y)
   bottom_right = (x + w, y + h)

   # Box params
   green = (0, 255, 0)
   thickness = 1  # pixels

   cv2.rectangle(
       img=morph_image, pt1=top_left, pt2=bottom_right, color=green, thickness=thickness
   )

cv2.imwrite("temp/OCR_each_word.png",morph_image)


True

In [51]:

def thick_font(image):
    image = cv2.bitwise_not(thresh)
    kernel = np.ones((1,1),np.uint8)
    image = cv2.dilate(image,kernel, iterations=1)
    image = cv2.bitwise_not(image)
    return image
    


In [52]:
dilated_image =thick_font(thresh)
cv2.imshow("img",dilated_image)
cv2.waitKey(0)

-1

In [91]:
decodec_text = pytesseract.image_to_string(morph_image)
decodec_text

"On Eastern frorning inl iid year 1945) 0 Rook my Bix-year-old\nson [by Eid hand and begar| walking from my homd flown foward fhe\nalleys and forests pf fia Carpathier hountaing.| For pearly\nBight MOHthS we Lived in BAFNS] BEECH and MAKeShITE GabinS] tH\ntha feneroug help OX an Pusually courazeous mani we fanaged to\nSurvive Europe's] greatest [it bf madness] (hose who walked fin\nihe pppesite direction on that Easter day were less fortunatel\nthey were taken inl Erainloada ta placeg whose onve pbseure hanes\n\nare flow, ahd Forever willl be, pynonymoug with terror evil and\n@eath) What follows [fq ourl tory of Gurvival fold fo tha Best\nbf my Bbility] inl plain] simple hanguage\nTH March of oh) hel SS ESOS HHO oven Ene internal laffeirg\n\nof Hungary and proceeded fod prganize thd beportation pz ews\nffol Eha Nazis this a foutind Assignment; within hours Bil Leal\npfficials Informed 62 bperationall he\nfasted a Uirectivd fesigned to placate [ewish Fears and induces\nae gnnounced {hat

In [71]:
lines = dict()
i=0
w=''
for line in decodec_text:
    w = w+line
    if line == "\n":
        lines[i]=w
        i=i+1
        w=''

In [72]:
lines

{0: '“GABRIEL Meamall —\n',
 1: '\n',
 2: 'On Easter morning in the year 1944, I took my six-year~old\n',
 3: 'son by the hand and began walking from my home town toward the\n',
 4: 'valleys and forests of the Carpathian mountains... For nearly\n',
 5: 'eight months we livea in barns, atties and makeshift cabins. With\n',
 6: 'the generous help of an unusually courageous man, we managed to\n',
 7: "survive Europe's greatest. fit of madness. Those who walked in\n",
 8: 'the opposite direction on that Easter day were less fortunate.\n',
 9: 'They were taken in trainloads to places whose once obscure names.\n',
 10: 'are now, and forever will be, synonymous with terror, evil and\n',
 11: 'death. What follows is our story of survival told to the best\n',
 12: 'of my ability, in plain, simple lariguage.\n',
 13: '\n',
 14: 'In March of 1944 the SS troops took over the internal. affeirs\n',
 15: 'of Hungary and proceeded to organize the deportation of the Tews.\n',
 16: 'fo the Nazis this va

In [12]:
context = {**lines}
print(context)


{0: 'The Life and Work of\n', 1: 'Fredson Bowers\n', 2: '\n', 3: 'by\n', 4: 'G. THOMAS TANSELLE\n', 5: '\n', 6: "'N EVERY FIELD OF ENDEAVOK- THERE ARE A FEW FIGURES WHOSE ACCOM-\n", 7: '\n', 8: 'plishmentand influence cause them to be the symbols of their age;\n', 9: '\n', 10: 'their careers and oeuvres become the touchstones by which the\n', 11: '\n', 12: 'field is measured and its history told. In the related pursuits of\n', 13: 'analytical and descriptive bibliography, textual criticism, and scholarly\n', 14: 'editing, Fredson Bowers was such a figure, dominating the four decades\n', 15: 'after 1949, when his Principles of Bibliographical Description was pub-\n', 16: 'lished. By 1973 the périod was already being called “the age of Bowers”:\n', 17: 'in that year Norman Sanders, writing the chapter on textual scholarship\n', 18: "for Stanley Wells's Shakespeare: Select Bibliographies, gave this title to\n", 19: 'a section of his essay. For mast people, it would be achicveruent enough\

In [10]:
im_file = "data/sign.jpg"
image = cv2.imread(im_file)
im_h, im_w, im_d = image.shape
print(image.shape)
base_image = image.copy()

(716, 2500, 3)


In [11]:
gray =cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Apply blur to gray image
blur = cv2.GaussianBlur(gray,(7,7),0)

# Convert blur image to thresh image(Binary image)
thresh = cv2.threshold(blur,210,230,cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

# Now we have to create a kernel object
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(5,13))

# Now apply dilation on the kernel
dilate = cv2.dilate(thresh,kernel,iterations=1)
cv2.imwrite("temp/OCR_dilate.png",dilate)

True

In [12]:
cv2.imshow("Original",dilate)
cv2.waitKey(0)

-1

In [6]:
gray =cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
thresh = cv2.threshold(gray,210,230,cv2.THRESH_BINARY)[1]

In [7]:
cnts = cv2.findContours(dilate, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if len(cnts) == 2 else cnts[1]
cnts = sorted(cnts, key=lambda x: cv2.boundingRect(x)[0])

In [8]:
for c in cnts:
    x,y,w,h = cv2.boundingRect(c)
    if  h>200 and w >20:
        roi = thresh[y:y+h, x:x+w]
        cv2.rectangle(image,(x,y),(x+w,y+h),(36,255,12),2)
        ocr_result = pytesseract.image_to_string(roi)
        # ocr_result = ocr_result.split("\n")
        print(ocr_result)

cv2.imwrite("temp/OCR_box.png",image)

True

In [9]:
image = cv2.imread(im_file)

In [11]:
text = pytesseract.image_to_string(image)

In [12]:
text

''

## NDArray to Image

In [1]:
import numpy as np
import cv2

In [2]:
image = np.zeros((500,500))
print(image)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
image[:,:] = 100
print(image)

[[100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 ...
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]]


In [4]:
image = image[:,:]+10
print(image)

[[110. 110. 110. ... 110. 110. 110.]
 [110. 110. 110. ... 110. 110. 110.]
 [110. 110. 110. ... 110. 110. 110.]
 ...
 [110. 110. 110. ... 110. 110. 110.]
 [110. 110. 110. ... 110. 110. 110.]
 [110. 110. 110. ... 110. 110. 110.]]


In [5]:
cv2.imwrite("Sample.jpg",image)

True

In [10]:
image[200:300,200:300]=255

In [7]:
cv2.imwrite("Sample.jpg",image)

True

In [8]:
image[:,:]=0

In [11]:
cv2.imwrite("Sample.jpg",image)

True

In [13]:
cv2.imshow('Test Image',image)
cv2.waitKey(0)

-1

## Drawing Lines, Shapes, Polygons, Texts

In [14]:
import cv2
import numpy as np

In [61]:
# Creating a canvas of three channel 500 X 500 pixels
canvas = np.zeros((500,500,3))
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

In [49]:
canvas.shape

(500, 500, 3)

In [22]:
# Drawing a Line
line=cv2.line(canvas,(100,100),(300,300),(0,255,0),2,cv2.LINE_AA)

In [23]:
cv2.imshow('Text Image',line)
cv2.waitKey(0)

-1

In [25]:
# Drawing a Rectangle
rect = cv2.rectangle(canvas,(200,200),(270,250),(0,0,255),-1)

In [26]:
cv2.imshow('Text Image',rect)
cv2.waitKey(0)

-1

In [27]:
# Drawing a circle
circle = cv2.circle(canvas,(300,300),70,(255,0,0),-1)

In [28]:
cv2.imshow('Text Image',circle)
cv2.waitKey(0)

-1

In [32]:
# Drawing a Arrow line
arrowline = cv2.arrowedLine(canvas,(400,400),(400,470),(255,255,255),2,tipLength=0.3)

In [33]:
cv2.imshow('Text Image',arrowline)
cv2.waitKey(0)

-1

In [35]:
# Drawing a Polygon
pts = np.array([[250,5],[220,80],[280,80]],np.int32)
pts = pts.reshape((-1,1,2))

polygon = cv2.polylines(canvas,[pts],True,(0,255,0),3)

In [37]:
cv2.imshow('Text Image',polygon)
cv2.waitKey(0)

-1

In [62]:
#Drawing Texts
fonts = [
    cv2.FONT_HERSHEY_COMPLEX,
    cv2.FONT_HERSHEY_DUPLEX,
    cv2.FONT_HERSHEY_PLAIN,
    cv2.FONT_HERSHEY_SCRIPT_SIMPLEX
]

position = (40,30)
for i in range(0,4):
    cv2.putText(canvas,"I am Deba",position,fonts[i],1,(255,255,255),2,cv2.LINE_AA)
    position = (position[0],position[1]+40)

In [63]:
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

## Analog Clock

In [9]:
import cv2
import numpy as np

In [16]:
# Creating a canvas of three channel 500 X 500 pixels
canvas = np.zeros((640,640,3),dtype = np.uint8)
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

In [11]:
x_coordinate = 580
y_coordinate = 320
hour_init = (x_coordinate,y_coordinate)

x_coordinate = 560 # 320 - ((260-20) * cos(0))
y_coordinate = 320 # 320 - ((260-20) * sin(0))
hour_dest = (x_coordinate,y_coordinate)

In [12]:
line = cv2.line(canvas,hour_init,hour_dest,(0,255,0),2,cv2.LINE_AA)

In [13]:
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

In [14]:
circle = cv2.circle(canvas,(320,320),260,(255,0,0),2)

In [15]:
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

In [17]:

canvas[:] = [255,255,255]
cv2.imshow('Text Image',canvas)
cv2.waitKey(0)

-1

In [22]:
from datetime import datetime
timenow = datetime.now()
timenow

datetime.datetime(2024, 9, 20, 16, 25, 5, 668723)

In [35]:
import datetime
timenow = datetime.datetime.now()
timenow.second

31

In [21]:
# Drawing
image = np.zeros((500,500))
image[:,:] = 100
print(image)


[[100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 ...
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]
 [100. 100. 100. ... 100. 100. 100.]]


In [22]:
image[0:100,0:100]=0
cv2.imshow('First 100 pixel black',image)
cv2.waitKey(0)

-1

In [23]:
image[200:300,0:100]=0
cv2.imshow('Second 100 pixel black',image)
cv2.waitKey(0)

-1

In [24]:
image[400:500,0:100]=0
cv2.imshow('Third 100 pixel black',image)
cv2.waitKey(0)

-1

In [25]:
image[100:200,100:200]=0
cv2.imshow('First column 100 pixel black',image)
cv2.waitKey(0)

-1

In [26]:
image[300:400,100:200]=0
cv2.imshow('Second column 100 pixel black',image)
cv2.waitKey(0)

-1

In [27]:
image[0:100,200:300]=0
image[0:100,400:500]=0
cv2.imshow('100 pixel black',image)
cv2.waitKey(0)

-1

In [29]:
image[100:200,300:400]=0
cv2.imshow('100 pixel black',image)
cv2.waitKey(0)

-1

In [33]:
image[200:300,200:300]=0
image[400:500,200:300]=0
cv2.imshow('100 pixel black',image)
cv2.waitKey(0)

-1

In [35]:
image[300:400,300:400]=0
cv2.imshow('100 pixel black',image)
cv2.waitKey(0)

-1

In [37]:
image[200:300,400:500]=0
image[400:500,400:500]=0
cv2.imshow('Chess Board',image)
cv2.waitKey(0)

-1

In [38]:
cv2.imwrite("Chess Board.jpg",image)

True